### ISSUE TITLE
Review theme for wp.org

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/shop-isle-wporg#3]

**Comment by HardeepAsrani** [comment]
- **Not required:** The following should appear only on singular pages when comments are enabled:

`<link rel="pingback" href="<?php bloginfo( 'pingback_url' ); ?>">`

- **Required:** The theme should use built-in logo functionality instead of a custom logo

- **Required:** More than one text-domain is being used in this theme. This means the theme will not be compatible with WordPress.org language packs. The domains found are shop-isle, woocommerce

- **Required:** Slider will fall under custom content creator as it's also adding text apart from images. 

- **Required:** Provide a unique prefix for everything the Theme defines in the public namespace, including options, functions, global variables, constants, post meta, etc.

  - Found some functions which are not prefixed properly, like `woocommerce_header_add_to_cart_fragment`, `wp_themeisle_customize_preview_js` 

- **Required:** Image sizes should be inside the setup function, including the one in woocommerce/functions.php file.

- **Required:** Content width should also be inside the setup function.

- **Required:** You should not prefix libraries, like bootstrap and/or font-awesome.

- **Required:** Declare licenses of any resources included such as fonts, images, scripts and styles in readme.txt file.

- **Required:** Everything needs to be escaped, like banner URLs and all the custom data.

That's all I found in this short review. Must be some issues that I missed.

**Comment by rodica-andronache** [comment]
@HardeepAsrani thanks :) I broke this in single issues. 
Regarding the slider, this is not allowed, but how about the other repeaters we are using, like the ones for Banners? @ineagu should we remove the slider?

**Comment by ineagu** [comment]
I would keep the slider and see with the admin reviewer.

**Comment by HardeepAsrani** [comment]
It's really up to the admin reviewing. Keeping it is worth a shot. :)
